### ISSUE TITLE
How to start this project?

### ISSUE THREAD

**Issue by qianqi0614** [JustForFunDeveloper/ShootingWebAgent#1]
Could you give a 'readme.md' file?

**Comment by JustForFunDeveloper** [comment]
Hi this is an old ASP.NET Core application from me which uses .NET Core 3.1.
Just clone it with Visual Studio and make sure you have .NET Core 3.1 SDK installed.

Just for your information this application is far from finished.
It just basically has an integrated API where Data can be send  to display shooting records from an electronic shooting range. (DISAG https://www.disag.de/)
If you start with the sample data included in the sqLite DB then just click on "MyMatchName" of the index View and see some fancy looking svg's.
This svg's are updated via SignalR when data is received through the integrated API.

That's basically it.
Have Fun!
